### ISSUE TITLE
Feature Request: Support for SDFs in both Shader and GN Seamlessly

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [Tams3d/T3D-GN-Presets#14]
The [B3DSDF](https://github.com/williamchange/b3dsdf) is a addon achieve the sdf in shader.
If you could make a addon which mix the shader and GN with them. It will be more powerful even add it to the official addon groups.

**Comment by Tams3d** [comment]
Hey!
Thanks for the suggestion. The current version of the addon **v1.1.0** contains SDF which are brought to Goemetry Nodes with **B3DSDF** as a reference. 
The next release of the addon **v1.2.0** (which is commited before few days as a Beta 🟡) provides much more control and accurate results.

Mixing of shader and geometry node SDFs - their are currently no plans to develop a feature or a seperate addon. **Named Attributes** can be used to get the Geometry nodes attributes to the Shader Node Editor, i would recommend a try for that.

Incase of any further information, feel free to continue the issue forward.

Thankyou 🤍

**Comment by Tams3d** [comment]
Closing this Issue for sake of the New Release which got extensive support for SDF as well as Fields to work correctly with Empty objects or any other Objects. SDF can be controlled using Empty Objects with the help of the `Transforms To Vector` node. Fields have direct input of Location, Rotation & Scale. Use the **Object Info** node to get Objects Location, Rotation & Scale information.
