### ISSUE TITLE
Feature Request: Add Vertex of edge node

### ISSUE THREAD

**Issue by crantisz** [Tams3d/T3D-GN-Presets#20]
**Is your feature request related to a problem? Please describe.**
It is hard to get vertices of edge. Edge vertices have no Weights and Index inputs, so that it works only from context. Corners of edge have only one corner per edge, so that it doesn't work with non-manifold geometry. So I Made my own Vertices of Edge node, please add this:

![Снимок экрана от 2024-07-10 13-20-12](https://github.com/Tams3d/T3D-GN-Presets/assets/1749968/f4c0b414-d87a-4f8f-b32d-c58fc50ca394)

**Comment by Tams3d** [comment]
I'm still unaware of the use cases of Mesh Topology nodes and I don't have complete knowledge about its functionality, still I feel it would be better to include this. I have slightly modified to fit along with category of other nodes. I would like to get your feedback with some potential use case.
![Screenshot 2024-07-12 190314](https://github.com/user-attachments/assets/1ce2a1de-0c84-4604-a634-499fb1a800fb)
![Screenshot 2024-07-12 190331](https://github.com/user-attachments/assets/b964950d-d1c2-487a-8420-b89120cc5082)

**Comment by crantisz** [comment]
Sort index is unnecessarily here, because you have always 2 vertices per edge, both of them are outputted.

**Comment by crantisz** [comment]
Here is an example of usage: https://blender.stackexchange.com/a/321401/32374

**Comment by Tams3d** [comment]
Your **Vertex of Edge** node feature request has been accepted and implemented in **T3D GN Presets** (v1.5.1). Users can find the node at T3D GN Presets > Mesh > Vertex of Edge (under Topology).

A Release with this change included will be scheduled Today in GitHub as well as in Blender Extensions. If you need any further assistance with the updates or anything else, feel free to Open the issue again.

**Commit: [(141cbff)](https://github.com/Tams3d/T3D-GN-Presets/commit/141cbff)**
