### ISSUE TITLE
Bug Report: Poll method for NODE_OT_group_add tries to access context.space_data.node_tree even if node_tree does not exist

### ISSUE THREAD

**Issue by The-Ratner** [Tams3d/T3D-GN-Presets#21]
If the active spaceView3d is not one that has a node_tree component (ie, it's not a node editor panel), pressing spacebar makes the console print AttributeError: 'SpaceView3D' object has no attribute 'node_tree'. "SpaceView3d" can also be any other view that the mouse is currently hovering over.
 It's not a critical issue, but I use the console a lot, so having error messages get spammed there can be pretty annoying if I'm working on other stuff that prints to the console.

To fix it, I'd recommend just replacing line 142 (the poll classmethod for NODE_OT_group_add)

changing it from:
```python
return context.space_data.node_tree
``` 
to
```python
return hasattr(context.space_data, 'node_tree')
``` 
which should do the same thing but without the error message.

![err1](https://github.com/user-attachments/assets/608f61d8-204a-4376-b0d5-7cfeb9f22a73)

**Comment by Tams3d** [comment]
Thank you for your patience. This issue has now been resolved. 
**Commit:** (https://github.com/Tams3d/T3D-GN-Presets/commit/25bdae528851f332fd42b9483d0886cf71013c8a).

Please note that the change won't be reflected in the **Extensions Platform** until the next release. I'm working to ensure that the update is incorporated as soon as possible.

If you encounter any further issues or have additional questions, feel free to let me know.
