### ISSUE TITLE
Bug Report: "Is inside Volume" does not work with points at object/world origin

### ISSUE THREAD

**Issue by AlienXtream** [Tams3d/T3D-GN-Presets#22]
### **Describe the bug**

When evaluating the raycast for the volume check the ray originating at 0,0,0 internally will always return false.

### **To Reproduce**

Steps to reproduce the behaviour:
 Add a grid (or any object with a vertex or evaluation point exactly at the object's origin). 
 
 apply the "Is Inside Volume" node with a suitable bounding mesh (a cube was used in testing) and preview data on the respective domain.
 
 you should see that the point at the origin always returns false, regardless of if it is inside the volume or not

### **Expected behaviour**

While the erroneous result makes sense when looking at the node group (a ray cast from 0,0,0 with the direction of 0,0,0 is obviously a null vector) this contradicts the intended function of the node. a robust solution that can compensate for the edge case of 0,0,0 should be implemented if possible.

### **Desktop (please complete the following information):**

- OS: Win10
- Blender 4.3.0
- Addon Version 1.5.2

### **Screenshots**

![image](https://github.com/user-attachments/assets/85cbd693-490e-4cbf-b3c1-654b308d8c6b)
![image](https://github.com/user-attachments/assets/4c89a9b0-a340-470c-b7db-1a733b3b2a99)

### **Additional context**

Add any other context about the problem here. (blend file or a video clip)

**Comment by AlienXtream** [comment]
i have modified the node group on my end as shown below. in essence, by comparing the position vector to 0,0,0 and using the boolean result (through a multiply node to reduce the offset to 0.001) as an addition to the position before the raycast and dot products are calculated seems to resolve the issues. though exact implementation may require some tweaking to be ideal for deployment i believe this is a stable approach for resolving this case.

![image](https://github.com/user-attachments/assets/a9fa3511-2fff-4573-abe4-538cf88ac27c)

**Comment by Tams3d** [comment]
Thank you for the bug report! I was able to reproduce the issue with the raycast from the origin (0,0,0) always returning false. To resolve this, I rewrote the node with 6 raycasts from different directions, ensuring the node evaluates the volume more reliably, even when the point of evaluation is at the origin. This approach was adapted from the deprecated Mesh To Field node. I have attached the test results.

## Volume fall-off selection
![is_inside_volume_01](https://github.com/user-attachments/assets/dfe15a2c-0ecb-41dc-bb2d-6f80eab71173)
## Deleting Points outside Volume
![is_inside_volume_02](https://github.com/user-attachments/assets/0827cd1c-c3d6-4973-9f88-242edd86c668)
- I keep issue open until, the node is made completely functional. I have included the .blend file containing **Is Inside Volume** node for your use case and testing purposes, download it from [here](https://www.dropbox.com/scl/fi/wqus1ds762qv1xx02s3vv/is_inside_volume.blend?rlkey=w1l1s5cae66lnxkrk8wi9xg4o&st=nyqjwohq&dl=0).

**Comment by Tams3d** [comment]
Thank you for your patience!
The issue has now been fixed and will be included in the next release.
**Commit**: [(2d2d8de)](https://github.com/Tams3d/T3D-GN-Presets/commit/2d2d8dead35e10b928d07accb2f8b43763a01d64)
